name: Deploy Next.js Static Site to HostGator

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build static Next.js site
        run: npm run build

      - name: Upload new release
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: 'out/*'
          target: '/home/${{ secrets.SSH_USER }}/releases/deploy-${{ github.run_number }}'
          use_insecure_cipher: true

      - name: Swap symlink to new release & preserve .well-known
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          use_insecure_cipher: true
          script: |
            TIMESTAMP="deploy-${GITHUB_RUN_NUMBER}"
            RELEASE_DIR="/home/${{ secrets.SSH_USER }}/releases/$TIMESTAMP"

            # Ensure releases and well-known folders exist
            mkdir -p ~/releases
            mkdir -p ~/well-known

            # Symlink .well-known into the new release
            ln -sfn ~/well-known $RELEASE_DIR/.well-known

            # Swap public_html symlink to point to the new release
            ln -sfn $RELEASE_DIR ~/public_html

            # Keep only the last 3 releases (1 active + 2 backups)
            cd ~/releases
            ls -t | tail -n +4 | xargs rm -rf || true

      - name: Mark latest commit as deployed
        run: npm run mark-deployed
