name: CI Tests

on:
  pull_request:
    branches: [master, development]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 22.9.0
      - run: yarn
      - run: yarn test
